### ISSUE TITLE
Cannot run server backend unless PHP config changes are made

### ISSUE THREAD

**Issue by blakestone95** [blakestone95/AshkeepersRestWebsite#35]
Description:
Cannot run server backend unless PHP config changes are made.  Please update the README to include the steps to modify the `php.ini` file.

Reproduction steps:
1. Follow backend setup steps
2. Run `php artisan migrate`
3. Get error

Error message (optional):
Illuminate\Database\QueryException  : could not find driver (SQL: select * from information_schema.tables where table_schema = 73rdlegionwebsite and table_name = migrations)

**Comment by dakriy** [comment]
Have you tried docker? On the new move-to-docker branch of course once that gets merged...
