### ISSUE TITLE
Change name of group everywhere it is referenced.

### ISSUE THREAD

**Issue by dakriy** [blakestone95/AshkeepersRestWebsite#38]
Description:
As should be obvious to most people reading this, the name should get changed, and possibly the repo moved to reflect the new name.

Acceptance Criteria:
- Name references changed in backend
- Name references changed in frontend
- Name references changed in config and services.
- Possibly change repo name or move it...

**Comment by blakestone95** [comment]
Agreed. Will stared addressing today (9/19) at the Dev Session.

**Comment by blakestone95** [comment]
Repo name changed

**Comment by blakestone95** [comment]
I think I got everything.  If anything was missed, change it when you see it.
