### ISSUE TITLE
Add Get, Create, and Delete endpoints for Events

### ISSUE THREAD

**Issue by blakestone95** [blakestone95/AshkeepersRestWebsite#52]
Description:
We need server endpoints to retrieve and manipulate events (extension of #22).

Acceptance Criteria:
- Can get list of events
  - Order descending by start date
  - Accepts optional date range parameter (default to all dates)
  - Supports pagination:
    - Accepts optional "# per page" parameter (default to 10)
    - Accepts optional "page #" parameter (defaults to 1)
- Can get single event by ID
- Can create single event
  - ID generated server-side or on DB, client shouldn't have to worry about that
- Can modify single event by ID
- Can mass delete events
  - Accepts an array of ID's to cover both the single delete and multiple delete cases

**Comment by dakriy** [comment]
Done in #58

**Comment by dakriy** [comment]
I'm closing this because it's done
